version: '3'
services:
    redis: 
        image: 'redis'
        ports: 
            - 6379:6379
    mongo:
        image: mongo
        ports: 
            - 27000:27017
    node-app:
        ports:
            - 5500:3000
        build:
            context: .
        environment:
            - NODE_ENV=development
            - REDIS_PORT=6379
            - MONGODB_URI=mongodb://mongo:27017/securityComposeDb
            - REDIS_URL=redis://6379
        depends_on:
            - redis
            - mongo