version: '3'
services:
    redis: 
        image: 'redis'
        ports: 
            - 6379:6379
    node-app:
        ports:
            - 3000:3000
        build:
            context: .
        environment:
            - NODE_ENV=development
            - REDIS_PORT=6379
            - REDIS_HOST=redis
        depends_on: 
            - redis